{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK"},"metadata":{"externalID":"TapiSDK","roleHeading":"Framework","role":"collection","modules":[{"name":"TapiSDK"}],"title":"TapiSDK","symbolKind":"module"},"hierarchy":{"paths":[[]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/tapisdk"]},{"paths":["\/documentation\/tapisdk"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager"],"title":"Classes"},{"title":"Protocols","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiDelegate"]},{"title":"Structures","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/ActionsResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CancelCheckoutResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardDetails","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardImpression","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardInformation","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardPayload","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutChangePaymentResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Customer","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CustomerDevice","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CustomerResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Discount","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressCustomer","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressDiscount","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressEmployee","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressItem","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressOrder","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Order","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/PingResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Product","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/RefundResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/StartCheckoutResponse","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiConfiguration"]},{"title":"Enumerations","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/ActionStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CancelCheckoutStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutChangePaymentStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/DeviceState","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/PaymentChangeType","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/RefundStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/StartCheckoutRequestStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiAction","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiEnvironment","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiEvent","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSkipOption","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TransactionStatus","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TransactionType"]}],"references":{"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CardInformation":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardInformation","kind":"symbol","navigatorTitle":[{"text":"CardInformation","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"CardInformation"},{"type":"text","text":" object represents the details of a card payment. It is sent as part of a "},{"code":"cardPresent","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"cardNotpresent"},{"type":"text","text":" "},{"type":"codeVoice","code":"TransactionType"},{"type":"text","text":"."}],"title":"CardInformation","url":"\/documentation\/tapisdk\/cardinformation","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardInformation","kind":"identifier"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CustomerDevice":{"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CustomerDevice","title":"CustomerDevice","kind":"symbol","navigatorTitle":[{"text":"CustomerDevice","kind":"identifier"}],"url":"\/documentation\/tapisdk\/customerdevice","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"CustomerDevice"},{"type":"text","text":" is effectively the state of the cPay device."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"CustomerDevice","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/StartCheckoutResponse":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/StartCheckoutResponse","type":"topic","abstract":[{"type":"text","text":"The initial status of a given "},{"code":"checkout","type":"codeVoice"},{"text":" request sent to the ","type":"text"},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"checkout","type":"codeVoice"},{"type":"text","text":" request will first initiate a checkout flow and return a "},{"code":"StartCheckoutResponse","type":"codeVoice"},{"type":"text","text":", then go into long polling and send "},{"code":"CheckoutResponses","type":"codeVoice"},{"type":"text","text":" as needed."}],"title":"StartCheckoutResponse","url":"\/documentation\/tapisdk\/startcheckoutresponse","role":"symbol","navigatorTitle":[{"text":"StartCheckoutResponse","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"StartCheckoutResponse","kind":"identifier"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CheckoutResponse":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CheckoutResponse","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutResponse","url":"\/documentation\/tapisdk\/checkoutresponse","title":"CheckoutResponse","kind":"symbol","role":"symbol","abstract":[{"text":"The resulting status of a given ","type":"text"},{"type":"codeVoice","code":"checkout"},{"type":"text","text":" request sent to the "},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"checkout","type":"codeVoice"},{"type":"text","text":" request will first initiate a checkout flow and return a "},{"code":"StartCheckoutResponse","type":"codeVoice"},{"type":"text","text":", then go into long polling and send "},{"code":"CheckoutResponses","type":"codeVoice"},{"text":" as needed.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CheckoutResponse"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiEnvironment":{"kind":"symbol","type":"topic","url":"\/documentation\/tapisdk\/tapienvironment","navigatorTitle":[{"text":"TapiEnvironment","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The environment that TapiSDK should communicate with.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TapiEnvironment","kind":"identifier"}],"title":"TapiEnvironment","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiEnvironment"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CancelCheckoutStatus":{"abstract":[{"type":"text","text":"An enum that represents the result of a given "},{"type":"codeVoice","code":"cancelCurrentCheckout"},{"text":" request.","type":"text"},{"type":"text","text":" "},{"text":"This is returned as part of the ","type":"text"},{"type":"codeVoice","code":"CancelCheckoutResponse"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CancelCheckoutStatus","type":"topic","url":"\/documentation\/tapisdk\/cancelcheckoutstatus","navigatorTitle":[{"text":"CancelCheckoutStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CancelCheckoutStatus","kind":"identifier"}],"title":"CancelCheckoutStatus","role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CustomerResponse":{"url":"\/documentation\/tapisdk\/customerresponse","type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CustomerResponse","abstract":[{"text":"A response object that is returned when a customer state changes or as part of long polling for a customer.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"When a customer checks in, the "},{"type":"codeVoice","code":"Customer"},{"type":"text","text":" object will populate and can be used to personalize the experience to the customer by the POS."}],"title":"CustomerResponse","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CustomerResponse"}],"navigatorTitle":[{"text":"CustomerResponse","kind":"identifier"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CancelCheckoutResponse":{"kind":"symbol","abstract":[{"type":"text","text":"The result of a "},{"type":"codeVoice","code":"cancelCurrentCheckout"},{"text":" request sent to the ","type":"text"},{"type":"codeVoice","code":"TapiManager"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CancelCheckoutResponse","role":"symbol","title":"CancelCheckoutResponse","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CancelCheckoutResponse","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"CancelCheckoutResponse","kind":"identifier"}],"url":"\/documentation\/tapisdk\/cancelcheckoutresponse"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiEvent":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiEvent","navigatorTitle":[{"kind":"identifier","text":"TapiEvent"}],"title":"TapiEvent","abstract":[{"text":"An event is emitted from the TapiSDK back to its delegate through the ","type":"text"},{"type":"codeVoice","code":"tapiManager(didSendEvent:)"},{"type":"text","text":" method."},{"text":" ","type":"text"},{"type":"text","text":"These events contain various details about the event type as well as response objects for each."},{"type":"text","text":" "},{"text":"It is up to the client to process each event type they are concerned with.","type":"text"}],"type":"topic","url":"\/documentation\/tapisdk\/tapievent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapiEvent"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/Discount":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Discount"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Discount","kind":"identifier"}],"url":"\/documentation\/tapisdk\/discount","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"Discount"},{"type":"text","text":" represents an available discount for a given customer."}],"title":"Discount","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Discount","type":"topic","role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CheckoutStatus":{"role":"symbol","abstract":[{"type":"text","text":"The status of the resulting "},{"code":"checkout","type":"codeVoice"},{"text":" request. It is sent as part of the ","type":"text"},{"type":"codeVoice","code":"checkoutStatus"},{"text":" ","type":"text"},{"type":"codeVoice","code":"TapiEvent"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CheckoutStatus"}],"navigatorTitle":[{"text":"CheckoutStatus","kind":"identifier"}],"type":"topic","title":"CheckoutStatus","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutStatus","url":"\/documentation\/tapisdk\/checkoutstatus"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/InProgressEmployee":{"kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"InProgressEmployee","kind":"identifier"}],"abstract":[{"text":"A simple ","type":"text"},{"code":"Employee","type":"codeVoice"},{"text":" type that is captured as part of a ","type":"text"},{"type":"codeVoice","code":"InProgressOrder"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"InProgressEmployee","kind":"identifier"}],"url":"\/documentation\/tapisdk\/inprogressemployee","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressEmployee","title":"InProgressEmployee","role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/RefundStatus":{"navigatorTitle":[{"text":"RefundStatus","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"RefundStatus","kind":"identifier"}],"abstract":[{"text":"An enum representing the status of the ","type":"text"},{"type":"codeVoice","code":"refund"},{"type":"text","text":" request sent to the "},{"code":"TapiManager","type":"codeVoice"}],"title":"RefundStatus","url":"\/documentation\/tapisdk\/refundstatus","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/RefundStatus","role":"symbol","kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/RefundResponse":{"navigatorTitle":[{"kind":"identifier","text":"RefundResponse"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"RefundResponse","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of a "},{"code":"refund","type":"codeVoice"},{"text":" request sent to the ","type":"text"},{"code":"TapiManager","type":"codeVoice"},{"text":".","type":"text"}],"title":"RefundResponse","url":"\/documentation\/tapisdk\/refundresponse","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/RefundResponse","role":"symbol","kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TransactionStatus":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TransactionStatus","kind":"identifier"}],"navigatorTitle":[{"text":"TransactionStatus","kind":"identifier"}],"role":"symbol","title":"TransactionStatus","abstract":[{"type":"text","text":"The underlying status of the "},{"type":"codeVoice","code":"checkout"},{"text":" request.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TransactionStatus","url":"\/documentation\/tapisdk\/transactionstatus","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/PaymentChangeType":{"type":"topic","abstract":[{"type":"text","text":"When initiating a "},{"type":"codeVoice","code":"changePaymentType"},{"type":"text","text":" request, we accept a "},{"type":"codeVoice","code":"PaymentChangeType"},{"type":"text","text":"."}],"title":"PaymentChangeType","kind":"symbol","url":"\/documentation\/tapisdk\/paymentchangetype","navigatorTitle":[{"text":"PaymentChangeType","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PaymentChangeType"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/PaymentChangeType"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/InProgressCustomer":{"role":"symbol","title":"InProgressCustomer","abstract":[{"text":"A simple ","type":"text"},{"type":"codeVoice","code":"Customer"},{"type":"text","text":" type that is captured as part of a "},{"type":"codeVoice","code":"InProgressOrder"},{"text":".","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"InProgressCustomer","kind":"identifier"}],"type":"topic","url":"\/documentation\/tapisdk\/inprogresscustomer","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressCustomer","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InProgressCustomer"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiSDKVersionString":{"title":"TapiSDKVersionString","kind":"symbol","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSDKVersionString","url":"\/documentation\/tapisdk\/tapisdkversionstring","fragments":[{"text":"TapiSDKVersionString","kind":"identifier"}]},"https://docs.google.com/document/d/1ZJ24kKWTIwLcsPQzdxwzAhe99FWEvCzYgbQo0lzviFM/edit":{"titleInlineContent":[{"text":"here","type":"text"}],"type":"link","title":"here","identifier":"https:\/\/docs.google.com\/document\/d\/1ZJ24kKWTIwLcsPQzdxwzAhe99FWEvCzYgbQo0lzviFM\/edit","url":"https:\/\/docs.google.com\/document\/d\/1ZJ24kKWTIwLcsPQzdxwzAhe99FWEvCzYgbQo0lzviFM\/edit"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CardImpression":{"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardImpression","url":"\/documentation\/tapisdk\/cardimpression","title":"CardImpression","navigatorTitle":[{"text":"CardImpression","kind":"identifier"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardImpression","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"CardImpression","type":"codeVoice"},{"type":"text","text":" simply provides a high level model of the "},{"type":"codeVoice","code":"CardPayload"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"CardDetails"},{"type":"text","text":"."}],"kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/DeviceState":{"url":"\/documentation\/tapisdk\/devicestate","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/DeviceState","navigatorTitle":[{"text":"DeviceState","kind":"identifier"}],"abstract":[{"type":"text","text":"The device of the cPay machine."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DeviceState"}],"title":"DeviceState"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/InProgressDiscount":{"kind":"symbol","abstract":[{"type":"text","text":"A simple "},{"type":"codeVoice","code":"Discount"},{"text":"  type that is captured as part of a ","type":"text"},{"type":"codeVoice","code":"InProgressOrder"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"InProgressDiscount","kind":"identifier"}],"type":"topic","title":"InProgressDiscount","navigatorTitle":[{"text":"InProgressDiscount","kind":"identifier"}],"url":"\/documentation\/tapisdk\/inprogressdiscount","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressDiscount","role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CardPayload":{"abstract":[{"type":"text","text":"The card information, including the details and the zip code as entered into the "},{"type":"codeVoice","code":"ManualEntry"},{"type":"text","text":" form."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardPayload","title":"CardPayload","url":"\/documentation\/tapisdk\/cardpayload","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"CardPayload","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CardPayload"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CardDetails":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardDetails"}],"url":"\/documentation\/tapisdk\/carddetails","abstract":[{"type":"text","text":"The details of the card, after tokenization by VGS."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CardDetails","navigatorTitle":[{"text":"CardDetails","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"CardDetails"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK":{"title":"TapiSDK","abstract":[],"url":"\/documentation\/tapisdk","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/StartCheckoutRequestStatus":{"url":"\/documentation\/tapisdk\/startcheckoutrequeststatus","navigatorTitle":[{"text":"StartCheckoutRequestStatus","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"StartCheckoutRequestStatus","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/StartCheckoutRequestStatus","abstract":[{"type":"text","text":"The initial status of a "},{"type":"codeVoice","code":"checkout"},{"type":"text","text":" request."}],"role":"symbol","kind":"symbol","title":"StartCheckoutRequestStatus"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/InProgressItem":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InProgressItem"}],"url":"\/documentation\/tapisdk\/inprogressitem","title":"InProgressItem","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"InProgressItem"}],"role":"symbol","abstract":[{"type":"text","text":"A simple "},{"code":"Item","type":"codeVoice"},{"type":"text","text":" type that is captured as part of a "},{"type":"codeVoice","code":"InProgressOrder"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressItem"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/PingResponse":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PingResponse"}],"navigatorTitle":[{"text":"PingResponse","kind":"identifier"}],"role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"PingResponse","type":"codeVoice"},{"type":"text","text":" is sent when the manager is first initialized. It indicates if the "},{"code":"TapiSDK","type":"codeVoice"},{"type":"text","text":" was able to communicate with the cPay given the "},{"type":"codeVoice","code":"TapiConfiguration"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"It also provides metadata about the connection if one is established.","type":"text"}],"kind":"symbol","title":"PingResponse","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/PingResponse","type":"topic","url":"\/documentation\/tapisdk\/pingresponse"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/Order":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Order"}],"url":"\/documentation\/tapisdk\/order","abstract":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"Order"},{"type":"text","text":" is sent to "},{"code":"TapiManager","type":"codeVoice"},{"type":"text","text":" as part of a "},{"type":"codeVoice","code":"checkout"},{"text":" request. It represents the details of the order as it is being processed by the POS.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Order","navigatorTitle":[{"text":"Order","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"Order"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiDelegate":{"kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"TapiDelegate"},{"type":"text","text":" is responsible for sending events as well as presenting the manual entry "},{"code":"UIViewController","type":"codeVoice"},{"text":" in the case of a manual card entry flow.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiDelegate","role":"symbol","title":"TapiDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapiDelegate"}],"type":"topic","navigatorTitle":[{"text":"TapiDelegate","kind":"identifier"}],"url":"\/documentation\/tapisdk\/tapidelegate"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CheckoutChangePaymentResponse":{"navigatorTitle":[{"text":"CheckoutChangePaymentResponse","kind":"identifier"}],"title":"CheckoutChangePaymentResponse","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutChangePaymentResponse","kind":"symbol","abstract":[{"text":"The result of a ","type":"text"},{"type":"codeVoice","code":"changePaymentType"},{"type":"text","text":" request sent to the "},{"type":"codeVoice","code":"TapiManager"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CheckoutChangePaymentResponse"}],"url":"\/documentation\/tapisdk\/checkoutchangepaymentresponse","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/ActionStatus":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ActionStatus"}],"kind":"symbol","abstract":[{"type":"text","text":"An enum that represents the result of a given "},{"type":"codeVoice","code":"sendAction"},{"text":" request.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This is returned as part of the "},{"type":"codeVoice","code":"ActionsResponse"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/ActionStatus","type":"topic","url":"\/documentation\/tapisdk\/actionstatus","title":"ActionStatus"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiConfiguration":{"abstract":[{"type":"text","text":"The TapiConfiguration contains the building block information needed for TapiSDK to be able to communicate with cPay."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiConfiguration","url":"\/documentation\/tapisdk\/tapiconfiguration","title":"TapiConfiguration","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TapiConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TapiConfiguration"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiSkipOption":{"type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSkipOption","abstract":[{"type":"text","text":"Skip options provide a means for the POS to automatically skip functions within the cPay flow as deemed necessary."}],"url":"\/documentation\/tapisdk\/tapiskipoption","title":"TapiSkipOption","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TapiSkipOption","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TapiSkipOption"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/ActionsResponse":{"type":"topic","abstract":[{"type":"text","text":"The resulting status of a given "},{"type":"codeVoice","code":"sendAction"},{"text":" request sent to the ","type":"text"},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":"."}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionsResponse","kind":"identifier"}],"title":"ActionsResponse","navigatorTitle":[{"text":"ActionsResponse","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/ActionsResponse","url":"\/documentation\/tapisdk\/actionsresponse"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TransactionType":{"navigatorTitle":[{"kind":"identifier","text":"TransactionType"}],"abstract":[{"type":"text","text":"The type of transaction to perform."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TransactionType","kind":"identifier"}],"url":"\/documentation\/tapisdk\/transactiontype","title":"TransactionType","type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TransactionType","kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TapiManager"}],"navigatorTitle":[{"text":"TapiManager","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":" is the heart and soul of the "},{"type":"codeVoice","code":"TapiSDK"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It provides all interactions with Tapi and thus cPay."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager","type":"topic","title":"TapiManager","url":"\/documentation\/tapisdk\/tapimanager"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiSDKVersionNumber":{"kind":"symbol","url":"\/documentation\/tapisdk\/tapisdkversionnumber","title":"TapiSDKVersionNumber","role":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSDKVersionNumber","fragments":[{"kind":"identifier","text":"TapiSDKVersionNumber"}],"type":"topic","abstract":[]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiAction":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiAction","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TapiAction"}],"navigatorTitle":[{"text":"TapiAction","kind":"identifier"}],"title":"TapiAction","url":"\/documentation\/tapisdk\/tapiaction","role":"symbol","type":"topic","abstract":[{"text":"A TapiAction is a simple action the client POS can send to change the state of the current cPay device.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Making this call you can skip screens as they appear in real time."},{"text":" ","type":"text"},{"text":"For skipping screens, you can skip the approval screen, reward notification screen, tips screen, and the keypad screen.","type":"text"},{"text":" ","type":"text"},{"text":"For kiosk mode you can enable the screensaver.","type":"text"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/Product":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Product","kind":"identifier"}],"url":"\/documentation\/tapisdk\/product","abstract":[{"type":"text","text":"A "},{"code":"Product","type":"codeVoice"},{"text":" represents an item that is part of an ","type":"text"},{"code":"Order","type":"codeVoice"},{"type":"text","text":". It is sent to "},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":" as part of a "},{"code":"checkout","type":"codeVoice"},{"type":"text","text":" request."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Product","navigatorTitle":[{"text":"Product","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"Product"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/InProgressOrder":{"kind":"symbol","title":"InProgressOrder","url":"\/documentation\/tapisdk\/inprogressorder","role":"symbol","abstract":[{"type":"text","text":"The"},{"type":"codeVoice","code":"InProgressOrder"},{"type":"text","text":" type is used to send data to the cPay device that will then present to the customer a running line item display of the items in a given transaction."},{"type":"text","text":" "},{"type":"text","text":"See "},{"isActive":true,"identifier":"https:\/\/docs.google.com\/document\/d\/1ZJ24kKWTIwLcsPQzdxwzAhe99FWEvCzYgbQo0lzviFM\/edit","type":"reference"},{"text":" for more information.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"InProgressOrder","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/InProgressOrder","navigatorTitle":[{"text":"InProgressOrder","kind":"identifier"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/CheckoutChangePaymentStatus":{"url":"\/documentation\/tapisdk\/checkoutchangepaymentstatus","abstract":[{"text":"An enum that represents the resulting status of a ","type":"text"},{"code":"changePaymentType","type":"codeVoice"},{"type":"text","text":" request."},{"text":" ","type":"text"},{"type":"text","text":"This is returned as part of the "},{"type":"codeVoice","code":"CheckoutChangePaymentResponse"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CheckoutChangePaymentStatus","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/CheckoutChangePaymentStatus","navigatorTitle":[{"text":"CheckoutChangePaymentStatus","kind":"identifier"}],"kind":"symbol","title":"CheckoutChangePaymentStatus","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/Customer":{"url":"\/documentation\/tapisdk\/customer","type":"topic","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/Customer","abstract":[{"text":"An underlying type that defines a ","type":"text"},{"code":"Customer","type":"codeVoice"},{"type":"text","text":" to the POS."}],"title":"Customer","role":"symbol","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Customer"}],"navigatorTitle":[{"kind":"identifier","text":"Customer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager"]},{"identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSDKVersionNumber","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiSDKVersionString"],"title":"Variables"}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TapiSDK~1documentation~1TapiSDK~1TapiManager\/title","value":"TapiManager"},{"value":[{"kind":"identifier","text":"TapiManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TapiSDK~1documentation~1TapiSDK~1TapiManager\/fragments"}]}]}