{"identifier":{"url":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TapiManager","kind":"identifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"codeListing","syntax":"swift","code":["\/\/ A normal interaction to process a transaction through `TapiSDK` would be as follows.","\/\/ After conforming to the `TapiDelegate` protocol and implementing the required delegate methods.","","\/\/ Step 1: Initialize a `TapiManager` with an appropriate `TapiConfiguration`","let configuration = TapiConfiguration(environment: .staging,","                                      softwareID: softwareID,","                                      apiKey: apiKey,","                                      apiSecret: apiSecret,","                                      terminalID: terminalID,","                                      posID: posID)","let tapiManager = TapiManager(configuration, delegate: self)","\/\/ Step 2: Listen for `TapiEvent`s to be sent back via the delegate method and take action appropriately.","func tapiManager(_ tapiManager: TapiSDK.TapiManager, didSendEvent event: TapiSDK.TapiEvent) { }","\/\/ Step 2a: Send any necessary `TapiAction`s as needed to the cPay device or perform a refund through the `refund` method."," tapiManager.sendAction(.toggleScreensaver(true)) \/\/ Turns the screensaver on."," tapiManager.sendAction(.toggleScreensaver(false)) \/\/ Turns the screensaver off.","\/\/ Step 3: Initiate a checkout request through the `checkout` method of the `TapiManager`","tapiManager.checkout(order,","                     transactionType: transactionType)","\/\/ Step 3a: Send commands such as `cancelCurrentCheckout` or `changePaymentType` as needed.","tapiManager.cancelCurrentTransaction()","\/\/ Step 4: Issue a `resetSession` command upon exiting the POS register screen, etc. Possibly only initializing the object when the cashier is in the actual checkout screens of the POS app.","tapiManager.resetSession()"]}]}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/init(_:delegate:)"]},{"identifiers":["doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/cancelCurrentCheckout()-3q8zb","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/cancelCurrentCheckout()-8vbgs","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/changePaymentType(to:with:)-39sba","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/changePaymentType(to:with:)-61guh","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-2w6lt","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-3vxps","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/refund(referenceID:for:)-539er","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/refund(referenceID:for:)-6m3pu","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/resetSession()","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/restartSession()","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/sendAction(_:)-96lku","doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/sendAction(_:)-9gpon"],"title":"Instance Methods"}],"metadata":{"role":"symbol","title":"TapiManager","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TapiManager","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"TapiSDK"}],"roleHeading":"Class","navigatorTitle":[{"text":"TapiManager","kind":"identifier"}],"externalID":"c:@M@TapiSDK@objc(cs)TapiManager"},"variants":[{"paths":["\/documentation\/tapisdk\/tapimanager"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/tapisdk\/tapimanager"]}],"abstract":[{"type":"text","text":"The "},{"code":"TapiManager","type":"codeVoice"},{"type":"text","text":" is the heart and soul of the "},{"code":"TapiSDK","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It provides all interactions with Tapi and thus cPay."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/objc(pl)NSObject","doc:\/\/org.cocoapods.TapiSDK\/s7CVarArgP","doc:\/\/org.cocoapods.TapiSDK\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.TapiSDK\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.TapiSDK\/SQ","doc:\/\/org.cocoapods.TapiSDK\/SH"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/changePaymentType(to:with:)-39sba":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changePaymentType","kind":"identifier"},{"kind":"text","text":"("},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK17PaymentChangeTypeO","text":"PaymentChangeType"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CardInformation","kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK15CardInformationV"},{"kind":"text","text":"?) "},{"text":"async","kind":"keyword"}],"abstract":[{"text":"A means to change the current payment type for the given transaction.","type":"text"}],"url":"\/documentation\/tapisdk\/tapimanager\/changepaymenttype(to:with:)-39sba","title":"changePaymentType(to:with:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/changePaymentType(to:with:)-39sba","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/sendAction(_:)-9gpon":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAction"},{"text":"(","kind":"text"},{"text":"TapiAction","kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK0A6ActionO"},{"kind":"text","text":") "},{"text":"async","kind":"keyword"}],"title":"sendAction(_:)","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/sendAction(_:)-9gpon","url":"\/documentation\/tapisdk\/tapimanager\/sendaction(_:)-9gpon","abstract":[{"type":"text","text":"Sends a given "},{"type":"codeVoice","code":"TapiAction"},{"type":"text","text":" to the cPay through "},{"type":"codeVoice","code":"TapiSDK"},{"type":"text","text":"."}]},"doc://org.cocoapods.TapiSDK/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.TapiSDK\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK":{"role":"collection","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/tapisdk","title":"TapiSDK","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK"},"doc://org.cocoapods.TapiSDK/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager":{"title":"TapiManager","type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":" is the heart and soul of the "},{"type":"codeVoice","code":"TapiSDK"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"It provides all interactions with Tapi and thus cPay."}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager","url":"\/documentation\/tapisdk\/tapimanager","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TapiManager"}],"navigatorTitle":[{"text":"TapiManager","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/restartSession()":{"type":"topic","url":"\/documentation\/tapisdk\/tapimanager\/restartsession()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"restartSession","kind":"identifier"},{"text":"()","kind":"text"}],"title":"restartSession()","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/restartSession()","abstract":[{"type":"text","text":"Ensures the session has been reset completely and begins a new series of customer requests and responses."},{"text":" ","type":"text"},{"text":"This method could be used prior to calling checkout on an already instantiated ","type":"text"},{"type":"codeVoice","code":"TapiManager"},{"type":"text","text":" for example."}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-3vxps":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkout","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK5OrderV","text":"Order"},{"text":", ","kind":"text"},{"text":"transactionType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7TapiSDK15TransactionTypeO","text":"TransactionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"posCheckoutID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"appliedDiscounts","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"Discount","preciseIdentifier":"s:7TapiSDK8DiscountV","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"pointsOverride","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[{"text":"The checkout method provides the basis for performing a checkout through the ","type":"text"},{"code":"TapiSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/tapisdk\/tapimanager\/checkout(_:transactiontype:poscheckoutid:applieddiscounts:pointsoverride:)-3vxps","title":"checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-3vxps","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-2w6lt":{"kind":"symbol","title":"checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)","type":"topic","abstract":[{"type":"text","text":"The checkout method provides the basis for performing a checkout through the "},{"type":"codeVoice","code":"TapiSDK"},{"text":".","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"checkout","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:7TapiSDK5OrderV","text":"Order","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"transactionType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TransactionType","preciseIdentifier":"s:7TapiSDK15TransactionTypeO"},{"kind":"text","text":", "},{"text":"posCheckoutID","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"appliedDiscounts"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:7TapiSDK8DiscountV","text":"Discount","kind":"typeIdentifier"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"pointsOverride"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/checkout(_:transactionType:posCheckoutID:appliedDiscounts:pointsOverride:)-2w6lt","role":"symbol","url":"\/documentation\/tapisdk\/tapimanager\/checkout(_:transactiontype:poscheckoutid:applieddiscounts:pointsoverride:)-2w6lt"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/cancelCurrentCheckout()-8vbgs":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelCurrentCheckout","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"async"}],"title":"cancelCurrentCheckout()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/cancelCurrentCheckout()-8vbgs","type":"topic","role":"symbol","abstract":[{"text":"Attempts to cancel the current checkout transaction.","type":"text"}],"url":"\/documentation\/tapisdk\/tapimanager\/cancelcurrentcheckout()-8vbgs"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/sendAction(_:)-96lku":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sendAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"TapiAction","kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK0A6ActionO"},{"text":")","kind":"text"}],"role":"symbol","title":"sendAction(_:)","type":"topic","abstract":[{"type":"text","text":"Sends a given "},{"type":"codeVoice","code":"TapiAction"},{"type":"text","text":" to the cPay through "},{"code":"TapiSDK","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/tapisdk\/tapimanager\/sendaction(_:)-96lku","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/sendAction(_:)-96lku"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/refund(referenceID:for:)-539er":{"type":"topic","url":"\/documentation\/tapisdk\/tapimanager\/refund(referenceid:for:)-539er","abstract":[{"text":"Provides a means to refund a given transaction for a given amount.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/refund(referenceID:for:)-539er","title":"refund(referenceID:for:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refund"},{"text":"(","kind":"text"},{"text":"referenceID","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/resetSession()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetSession"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Resets the current sessions and kills any long polling requests that may be still outstanding."}],"url":"\/documentation\/tapisdk\/tapimanager\/resetsession()","title":"resetSession()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/resetSession()","type":"topic"},"doc://org.cocoapods.TapiSDK/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/changePaymentType(to:with:)-61guh":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"changePaymentType"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7TapiSDK17PaymentChangeTypeO","text":"PaymentChangeType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"CardInformation","kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK15CardInformationV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"A means to change the current payment type for the given transaction."}],"url":"\/documentation\/tapisdk\/tapimanager\/changepaymenttype(to:with:)-61guh","title":"changePaymentType(to:with:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/changePaymentType(to:with:)-61guh","type":"topic"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/refund(referenceID:for:)-6m3pu":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refund","kind":"identifier"},{"text":"(","kind":"text"},{"text":"referenceID","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"}],"role":"symbol","title":"refund(referenceID:for:)","type":"topic","abstract":[{"type":"text","text":"Provides a means to refund a given transaction for a given amount."}],"url":"\/documentation\/tapisdk\/tapimanager\/refund(referenceid:for:)-6m3pu","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/refund(referenceID:for:)-6m3pu"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/init(_:delegate:)":{"role":"symbol","abstract":[{"type":"text","text":"A convenience initializer to provide easy initialization of the "},{"type":"codeVoice","code":"TapiManager"}],"type":"topic","url":"\/documentation\/tapisdk\/tapimanager\/init(_:delegate:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"TapiConfiguration","preciseIdentifier":"s:7TapiSDK0A13ConfigurationV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"delegate"},{"kind":"text","text":": "},{"text":"TapiDelegate","kind":"typeIdentifier","preciseIdentifier":"s:7TapiSDK0A8DelegateP"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/init(_:delegate:)","title":"init(_:delegate:)","kind":"symbol"},"doc://org.cocoapods.TapiSDK/documentation/TapiSDK/TapiManager/cancelCurrentCheckout()-3q8zb":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cancelCurrentCheckout","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Attempts to cancel the current checkout transaction."}],"url":"\/documentation\/tapisdk\/tapimanager\/cancelcurrentcheckout()-3q8zb","title":"cancelCurrentCheckout()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.TapiSDK\/documentation\/TapiSDK\/TapiManager\/cancelCurrentCheckout()-3q8zb","type":"topic"},"doc://org.cocoapods.TapiSDK/SH":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.TapiSDK/SQ":{"identifier":"doc:\/\/org.cocoapods.TapiSDK\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"TapiManager"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"TapiManager","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TapiManager","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":null},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.TapiSDK\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TapiManager","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TapiManager","path":"\/references\/doc:~1~1org.cocoapods.TapiSDK~1documentation~1TapiSDK~1TapiManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.TapiSDK~1documentation~1TapiSDK~1TapiManager\/fragments","value":[{"kind":"identifier","text":"TapiManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}